### PR TITLE
Russian translation for US.MILE

### PR DESCRIPTION
**Pull request by Vorticity-Flux**

### CODE REVIEW

**Comment by keilw** [comment]
Thanks, I merged it into uom-se, please have a look there to verify: https://github.com/unitsofmeasurement/uom-se For process reasons only JCP Members shall directly contribute to the RI, plus we're pruning Locale and ResourceBundle in the RI for other formats, so will close this request here.

**Comment by Vorticity-Flux** [comment]
Yes, it's all right. Thank you.
I hope Java 7 version will not be left behind.

**Comment by keilw** [comment]
The RI while it works for Java 7 is intended for Embedded including ME Embedded, thus we leave things that won't work on Java ME or at least handle them differently.

**Comment by keilw** [comment]
We also plan to use Unicode CLDR definitions where applicable. At least for uom-se, if size permits also the RI. It provides numerous languages and translations for supported units out of the box: http://cldr.unicode.org/index/downloads

**Pull request closed without merging**
