### PR TITLE
Changing year length to 365.2425 days.

### PR DESCRIPTION
**Pull request by gerardvisser**
Since a Gregorian year has 97 leap years each 400 years the mean year length is:
(97×366+303×365)/400=365.2425

### CODE REVIEW

**Comment by keilw** [comment]
@gerardvisser Thanks, it looks like you did not include some JUnit tests to adopt the new exchange rates. Will fix it later.

**Comment by gerardvisser** [comment]
I'm sorry, I didn't realize. I can fix that as well.

**Comment by keilw** [comment]
How fast?

**Comment by gerardvisser** [comment]
I can have a look at it now: tomorrow I can't because of a company day that
lasts the whole day.
I take it that simply getting a converter and converting a year will do?

**Comment by keilw** [comment]
Sounds fine. I probably won't have time tonight as I worked very late on client stuff. Having a broken CI build of the master is not good, but for a day it seems acceptable. TIA

**Comment by gerardvisser** [comment]
I wrote a unit test and then realized I broke the build in QuantitiesTest: I fixed that too.
Do you want me to remove the added UnitsTest::teatMeanYearLength again?

**Pull request merged**
