### PR TITLE
Unused private fields should be removed

### PR DESCRIPTION
**Pull request by zeeshanasghar**
This pull request is focused on resolving occurrences of Sonar rule 

squid:S1068 Unused private fields should be removed

You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S1068

Please let me know if you have any questions.

Zeeshan Asghar

### CODE REVIEW

**Comment by keilw** [comment]
When do you plan to join the JCP? It is possible but takes time to factor that in manually. As long as a user is not an EG member, we cannot directly merge it as this becomes a "contribution" by GitHub.

**Comment by zeeshanasghar** [comment]
Can you guide me plz of how to join JCP ?

**Comment by keilw** [comment]
As a company, the current info is here: https://jcp.org/en/participation/membership2
Note, JCP is just being reformed, and PMO/Oracle no longer charges companies, so your organization could also join if they want. Contact pmo@jcp.org or heather@jcp.org for more information on joining the JCP.

**Comment by zeeshanasghar** [comment]
Hi, Yes, I join JCP,
and mail back JSPA that is requirement of join.

**Pull request closed without merging**
